### ISSUE TITLE
Doesn't work on twitter new layout.

### ISSUE THREAD

**Issue by aezakmil** [inDream/DownAlbum#13]
Doesn't work on twitter new layout.

**Comment by starobots** [comment]
Thanks for develop!
It doesn't work on the new version twitter.

**Comment by starobots** [comment]
Sorry to popup again, the extension doesn't works on the new mobile layout of twitter, How to switch to the old layout?

**Comment by inDream** [comment]
It should be fixed in version 0.20.2.1. (9371772506829702eeac021c1c2249b833d8abba)

**Comment by starobots** [comment]
Hi, dear developer. 
The extension doesn't load the files on the new layout twitter or the old twitter layout switched by the extension right now. 
Thanks for your working!

**Comment by aezakmil** [comment]
thx help
