### ISSUE TITLE
File name formats: $d (date) and $dc (date compact) don't work properly for Twitter downloads

### ISSUE THREAD

**Issue by AmperAndSand** [inDream/DownAlbum#15]
The file name formats, `$d` (date) and `$dc` (date compact) don't work properly for Twitter downloads. For example, Feb. 13, 2020 will show up as 52087-03-10 180320 for `$d` and 520870310 180320 for `$dc`. The dates won't be in the filename at all. This is a screenshot for a download at https://twitter.com/Twitter:

![downalbum date format issue](https://user-images.githubusercontent.com/1404745/74416545-42b28e80-4e80-11ea-8e36-61e738a75cde.png)

**Comment by inDream** [comment]
It should be fixed in version 0.20.2.2 (in review).
