### ISSUE TITLE
.mp4 files are not saved from Messenger (Facebook)

### ISSUE THREAD

**Issue by nx-frost** [inDream/DownAlbum#2]
Just finished a full scrape of my Facebook Messenger chat. 

Not a single .mp4 was saved, not sure as to why this would occur.

**Comment by vgchat** [comment]
It's called **DownAlbum** for a reason, as in PHOTO albums

**Comment by inDream** [comment]
You could export video link by "Tools -> Export Video Url", then use external downloader like JDownloader to batch download the videos.
