### ISSUE TITLE
Missing Pins

### ISSUE THREAD

**Issue by ghost** [inDream/DownAlbum#5]
The popup window says it has downloaded over 1,000 pins, but after saving the webpage, it only got around 200 pins.

I have large optimization enabled, and used normal mode.

**Comment by inDream** [comment]
Could you send me the link to test?

**Comment by ghost** [comment]
Here's the board that I am trying to download: https://www.pinterest.com/vkeusebio/inspirations/

**Comment by inDream** [comment]
I've tested and it works, here's the downloaded photos:
https://drive.google.com/file/d/1kewlUi75goqCOQySso0jPsaD_NMLgIWx
